"""empty message

Revision ID: 5575561ac04b
Revises: 4e13f8f8cdf4
Create Date: 2023-03-14 18:38:53.631737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5575561ac04b'
down_revision = '4e13f8f8cdf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keywords')
    )
    op.create_table('keywordsfavorites',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_keywords', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('id_keywords')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('id_keywords', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', 'new_id')
    )
    op.create_table('newsfavorites',
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=False),
    sa.Column('news_title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('favorite_new_source', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('news_id', 'reader_id')
    )
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_last_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', 'id_user')
    )
    op.create_table('widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('type_widget', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetfavorites',
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('lector_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_first_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('user_last_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.Enum('male', 'female', 'other', name='varchar'), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('user_last_name')
        batch_op.drop_column('user_first_name')
        batch_op.drop_column('user_name')

    op.drop_table('widgetfavorites')
    op.drop_table('widgets')
    op.drop_table('readers')
    op.drop_table('newsfavorites')
    op.drop_table('news')
    op.drop_table('keywordsfavorites')
    op.drop_table('keywords')
    op.drop_table('advertisers')
    # ### end Alembic commands ###
