"""empty message

Revision ID: 6d11a8a395f9
Revises: 
Create Date: 2023-03-14 21:09:47.921115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d11a8a395f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keywords')
    )
    op.create_table('News',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('new_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('published', sa.DateTime(), nullable=False),
    sa.Column('id_keywords', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('user_first_name', sa.String(length=120), nullable=False),
    sa.Column('user_last_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='varchar'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('Widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('type_widget', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('user_last_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KeywordsFavorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_keywords', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_keywords'], ['Keywords.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['Readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('NewsFavorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('news_title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.Column('favorite_new_source', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['News.id'], ),
    sa.ForeignKeyConstraint(['reader_id'], ['Readers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('WidgetFavorites',
    sa.Column('lector_id', sa.Integer(), nullable=False),
    sa.Column('reader_id', sa.Integer(), nullable=True),
    sa.Column('widget_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reader_id'], ['Readers.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['Widgets.id'], ),
    sa.PrimaryKeyConstraint('lector_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('WidgetFavorites')
    op.drop_table('NewsFavorites')
    op.drop_table('KeywordsFavorites')
    op.drop_table('Readers')
    op.drop_table('Advertisers')
    op.drop_table('Widgets')
    op.drop_table('User')
    op.drop_table('News')
    op.drop_table('Keywords')
    # ### end Alembic commands ###
