"""empty message

Revision ID: 8c520689a748
Revises: dc86d9b749fc
Create Date: 2023-03-20 17:56:22.137617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c520689a748'
down_revision = 'dc86d9b749fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KeywordsFavorites', schema=None) as batch_op:
        batch_op.drop_constraint('KeywordsFavorites_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])

    with op.batch_alter_table('NewsFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('NewsFavorites_reader_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.drop_column('reader_id')

    with op.batch_alter_table('WidgetFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('WidgetFavorites_reader_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.drop_column('reader_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WidgetFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('WidgetFavorites_reader_id_fkey', 'Reader', ['reader_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('NewsFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('NewsFavorites_reader_id_fkey', 'Reader', ['reader_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('KeywordsFavorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('KeywordsFavorites_user_id_fkey', 'Reader', ['user_id'], ['id'])

    # ### end Alembic commands ###
