"""empty message

Revision ID: c7045bb9e0e0
Revises: 6d11a8a395f9
Create Date: 2023-03-15 17:32:57.953690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7045bb9e0e0'
down_revision = '6d11a8a395f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('KeywordsFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('KeywordsFavorites_id_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Readers', ['user_id'], ['id'])
        batch_op.drop_column('id_user')

    with op.batch_alter_table('News', schema=None) as batch_op:
        batch_op.drop_column('new_id')

    with op.batch_alter_table('NewsFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.drop_column('news_title')

    with op.batch_alter_table('Readers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('Readers_id_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['id'])
        batch_op.drop_column('id_user')

    with op.batch_alter_table('WidgetFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.Integer(), nullable=False))
        batch_op.drop_column('lector_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('WidgetFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lector_id', sa.INTEGER(), server_default=sa.text('nextval(\'"WidgetFavorites_lector_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
        batch_op.drop_column('ID')

    with op.batch_alter_table('Readers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Readers_id_user_fkey', 'User', ['id_user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('NewsFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('title')

    with op.batch_alter_table('News', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('KeywordsFavorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('KeywordsFavorites_id_user_fkey', 'Readers', ['id_user'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
