"""empty message

Revision ID: d940e9df3591
Revises: 7295b33df7e4
Create Date: 2023-04-05 18:30:26.762957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd940e9df3591'
down_revision = '7295b33df7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Advertisers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('company_address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('CIF_NIF', sa.String(length=100), nullable=True))
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Advertisers', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('CIF_NIF')
        batch_op.drop_column('company_address')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###
