"""empty message

Revision ID: dc86d9b749fc
Revises: 8d9be7d05774
Create Date: 2023-03-20 17:44:00.808332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dc86d9b749fc'
down_revision = '8d9be7d05774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('News', schema=None) as batch_op:
        batch_op.alter_column('published',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('News', schema=None) as batch_op:
        batch_op.alter_column('published',
               existing_type=sa.String(length=100),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    # ### end Alembic commands ###
